const Head = () => {
  return (
    <>
      <title>Review me</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Next app" />
    </>
  );
};

export default Head;
